### ISSUE TITLE
bug: dash_vtk.PointCloudRepresentation does not accept 'id' as a valid keyword argument

### ISSUE THREAD

**Issue by PotofStew23** [plotly/dash-vtk#73]
#### Description
When supplying an id as a keyword argument to a PointCloudRepresentation, the following TypeError is raised:
TypeError: The `dash_vtk.PointCloudRepresentation` component (version 0.0.9) with the ID "vtkPointCloud" received an unexpected keyword argument: `id`
Allowed arguments: colorDataRange, colorMapPreset, property, rgb, rgba, scalars, xyz
#### Steps/Code to Reproduce

import dash
import dash_vtk
import dash_html_components as html

app = dash.Dash(__name__)

app.layout = html.Div(
    style={"width": "100%", "height": "calc(100vh - 16px)"},
    children=dash_vtk.View([
        dash_vtk.PointCloudRepresentation(
            id='vtk-pointcloud',
            xyz=[1, 1, 1, 2, 2, 2, 3, 3, 3],
            scalars=[1, 2, 3],
            colorDataRange=[1, 3],
            property={"pointSize": 5}
        ),
    ]),
)

if __name__ == "__main__":
    app.run_server(debug=True)

#### Expected Results

![image](https://github.com/plotly/dash-vtk/assets/133385408/347e6622-11af-488e-8427-b9311fbf192c)

#### Actual Results

Traceback (most recent call last):
    dash_vtk.PointCloudRepresentation(
  File "C:\...\.venv\lib\site-packages\dash\development\base_component.py", line 420, in wrapper
    return func(*args, **kwargs)
  File "C:\...\.venv\lib\site-packages\dash_vtk\PointCloudRepresentation.py", line 52, in __init__
    super(PointCloudRepresentation, self).__init__(**args)
  File "C:\...\.venv\lib\site-packages\dash\development\base_component.py", line 138, in __init__
    raise TypeError(
TypeError: The `dash_vtk.PointCloudRepresentation` component (version 0.0.9) with the ID "vtk-pointcloud" received an unexpected keyword argument: `id`
Allowed arguments: colorDataRange, colorMapPreset, property, rgb, rgba, scalars, xyz
#### Versions

Dash 2.13.0
Dash Core Components 2.0.14
Dash HTML Components 2.12.0
Dash VTK 0.0.9

**Comment by frouhi** [comment]
I'm wondering about this one too! did you manage to find a workaround?
